### ISSUE TITLE
Update Approved Domain Validation Methods

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#116]
CAB Forum ballot 218 proposes deprecating BR 3.2.2.4 methods 1 and 5 and adding a new method.

BR 3.2.2.4 methods 9 and 10 have known vulnerabilities and may also need to be retired.

Consider updating the policy to reflect these changes.

**Comment by sleevi** [comment]
Do you see 3.2.2.4.8 fitting into this, given 3.2.2.5 still allows "Any other method" ?

**Comment by wthayer** [comment]
I'm not aware of any discussion on 3.2.2.4.8 - I'd like to see that happen before we consider adding it to the list.

**Comment by sleevi** [comment]
3.2.2.4.8 uses 3.2.2.5, and 3.2.2.5 (4) is "Any other method"

Hence it's a loophole in the "10 blessed methods" of the current policy, and aligns with the set of concerns raised above about flexibility.

**Comment by wthayer** [comment]
Sure, but where do you draw the line? 3.2.2.4.6 is also underspecified.

**Comment by timfromdigicert** [comment]
I think the solution to Ryan's issue is to remove 3.2.2.5 (4).  The VWG is currently discussing changes to 3.2.2.5, and we haven't heard of any CA that is using it, though we should check the smaller ones.

It's possible 3.2.2.5 (4) could be removed with an aggressive timeline if it's really true no one is using it.

**Comment by sleevi** [comment]
@wthayer Perhaps this overlaps too much with #115, but I suppose my point was that if the concern with .9/.10 is the CA should disclose/have a mitigation plan/etc, then that would logically also apply to .8 (with respect to 3.2.2.5 (4)). If the goal is to have disclosure over the validation practices, then simply specifying 3.2.2.4.8 in a CP/CPS is probably not sufficient, and you'd need them to specify with of the 3.2.2.5 methods they're using are.

Alternatively, if you view .9/.10 as things to ban for the reasons of the risk, then .8 logically fits within that - both because as an IP-based control, it shares the same fundamental risk of .9/.10, and because as an underspecified method with known risks.

That's the logic that I'm applying here, and I think it's distinct enough from .6 to merit consideration
