### ISSUE TITLE
Audits are required even if no longer issuing

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#139]
CAs can't declare that they are no longer issuing certificates and therefore don't need to be audited. Clarify that audits are required until the CA certificate is revoked or removed.

**Comment by wthayer** [comment]
Need to address this objection that is commonly raised: Can a CA get an audit when not issuing any certs during the audit period?

**Comment by sleevi** [comment]
I'll see if we can get some formal guidance from our WebTrust TF liason in that role. This has been discussed at several WebTrust TF meetings as a need of browsers to provide consistence guidance, so if we can have something that at least WebTrust practitioners can refer to, then we can collaborate with the ETSI counterparts.

ETSI is trickier for non-performance, since as a certification scheme, non-performance suspends certification.

**Comment by sleevi** [comment]
@dzacharo No, qualified reports are not like that. And you don’t publish certificates in ETSI if you’re no longer able to do conformance assessments, which was the point.

**Comment by dzacharo** [comment]
I probably misunderstood the "non-performance" with "non-conformance" :) IMO, an audit must always be performed by CAs participating in the Mozilla Root Program even if the CA stops issuing certificates. The audit must ensure that proper controls to protect CA keys, critical assets, etc continue to work effectively and efficiently. Clauses related to Certificate Issuance will be out of audit scope but the Auditor must be able to make an assertion about this.

**Comment by sleevi** [comment]
Yes. And that works for WebTrust, as I mentioned in https://github.com/mozilla/pkipolicy/issues/139#issuecomment-394007691.

However, under the ETSI framework, the Certificate is only issued for performance of the activities and the scope being comprehensive. So if a CA is not issuing, then they cannot be issued a Certificate, which is what browsers currently use as the assessment result. Instead, we will need to work with ETSI to discuss, particularly with respect to the Conformity Assessment Report, to ensure Browsers are provided with the appropriate information.

As auditors do not necessarily publish CARs, even for clean audits, this requires work. That's why I said in https://github.com/mozilla/pkipolicy/issues/139#issuecomment-394007691 it will be trickier.

**Comment by BenWilson-Mozilla** [comment]
Language to address this could be added on to the end of the first sentence in the [Section 3.1.3 of the Mozilla Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#313-audit-parameters).  Note that this issue is related to [Issue 153](https://github.com/mozilla/pkipolicy/issues/153).
