### ISSUE TITLE
Describe actions Mozilla may take upon receipt of a qualified audit

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#155]
Set a norm in policy for the expected actions that will occur when Mozilla receives an audit containing serious qualifications, such as:
* opening a misissuance bug and requiring a CA to file an incident report on the qualifications
* requiring POT audits (WTCA, BR) once the qualification(s) have been remediated. The reports must state that 'as of X date, the issue was resolved'. Prefer POT with qualifications noted as resolved over PIT because POT is more comprehensive - might catch other problems.
* in addition, Mozilla may require more frequent POT audits to regain confidence in the CA.

Of course, leave plenty of room for discretion to match specific circumstances, up to an including removing the CA from the program.

Consider applying these norms to any issue that is discovered, not just audit qualifications.

**Comment by BoryanaUri** [comment]
For ETSI/ACAB’c audits a CA with audit non-conformities are already treated exactly that way: Implementation dates can be suggested by the CA. They are discussed and agreed upon by all parties. After implementation, a check is performed by the auditors in order to verify the taken measures and how the CA avoids similar incidents/non-conformities in the future. 

Best regards
Boryana & Clemens

**Comment by sleevi** [comment]
This is not exactly the same. This is about notifying Mozilla the moment non-conformities are identified, and ensuring that Mozilla has supervision in the resolution of these non-conformities. Mozilla is not presently being consulted by the auditors consistently, because this is not a requirement for accredited auditors performing such ETSI audits, and ACAB'c is entirely voluntary.

**Comment by BenWilson-Mozilla** [comment]
Issue #150 seems very similar, and I think that one can be closed.

**Comment by BenWilson-Mozilla** [comment]
- Require revocation of leaf certificates
- Require revocation of Intermediate CAs
- Intermediate CA(s) added to One CRL
- Bugzilla Incident Reporting (Weekly)
- Point-in-Time audit to show that underlying issues have been fixed
- Plan of Action and Milestones
- 60-day Period-of-Time Audits
- Detailed controls audit report
- Websites trust bit removal
- Root Removal

**Comment by BenWilson-Mozilla** [comment]
Public discussion of this issue started here:  https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/KO3dK3QU-aQ/m/yJ4Sc2oIAgAJ

**Comment by wthayer** [comment]
@BenWilson-Mozilla I'd suggest clarifying the section 2.4 expectation for creating incidents when an audit lists multiple "matters". Should a CA create one incident per matter? I suspect that is Mozilla's desire, but CAs will create one per audit report (or set of audit reports). Perhaps this level of details doesn't belong in policy but could be made clear on the wiki.

**Comment by BenWilson-Mozilla** [comment]
@wthayer In the wiki, I added language to https://wiki.mozilla.org/CA/Responding_To_An_Incident#Incident_Report, "There should be a single incident report for each distinct matter, and CA operators should submit an additional, separate incident report when:  ... An audit report or conformity assessment contains more than one qualification, major non-conformity, or other adverse finding."
