### ISSUE TITLE
Require EKUs in EE Certs

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#163]
Consider adding a requirement for EE certificates to include the extendedKeyUsage extension.

The BRs require EKUs in leaf TLS certs, but there is no similar requirement for S/MIME in Mozilla policy. This can be a policy issue when a leaf certificate signed by a intermediate without an EKU contains no EKU. Is that leaf certificate required to comply with the BRs? What if it otherwise looks like an S/MIME certificate?

**Comment by wthayer** [comment]
The apparent lack of a standardized EKU for document signing may block this proposal.

**Comment by RufusJWB** [comment]
fyi: We at Siemens have both id_kp_clientAuth (1.3.6.1.5.5.7.3.2) and id_kp_emailProtection (1.3.6.1.5.5.7.3.4) in our S/MIME EE authentication certificates and never received any complaint from our 400k subjects, that someone was not able to sign a document (e.g. PDF or Word) or an email. This is obviously no proof, that there might not be any client software in the field that has specific requirements, but it is at least a good indication.

**Comment by RufusJWB** [comment]
@weirdscience Do you also separate between encryption and authentication?

**Comment by weirdscience** [comment]
Yes, signature, encryption, and authentication are separated.

Cert profiles are at https://www.idmanagement.gov/fpki/

**Comment by briansmith** [comment]
> Is that leaf certificate required to comply with the BRs?

Clients (including Mozilla's) will accept certificates without an explicitly-encoded EKU because no EKU extension means "valid for all EKUs". Thus, any certificate without an EKU extension should be required to comply with the BRs if it chains up to a root that is trusted for TLS. Further, a lot of software, including Mozilla's, doesn't support `anyExtendedKeyUsage`, so the only portable way to encode `anyExtendedKeyUsage` is to avoid including the EKU at all.

**Comment by wthayer** [comment]
Conclusion from the discussion is that we should not implement this proposal: https://groups.google.com/d/msg/mozilla.dev.security.policy/5lAI-8lkQbM/1D392GR1BQAJ

**Comment by wthayer** [comment]
More discussion resulted in a desire to include this in policy after all.
