### ISSUE TITLE
Update Section 5.1 about allowed ECDSA curve-hash pair

### ISSUE THREAD

**Issue by dzacharo** [mozilla/pkipolicy#170]
Section 5.1's language seems ambiguous because it doesn't clarify whether the allowed curve-hash pair is related to the CA key or the Subject Key. Here is a proposed change:

# ORIGINAL

Root certificates in our root program, and any certificate which
chains up to them, MUST use only algorithms and key sizes from the following
set:

*   RSA keys whose modulus size in bits is divisible by 8, and is at
    least 2048.
*   Digest algorithms: SHA-1 (see below), SHA-256, SHA-384, or SHA-512.
*   ECDSA keys using one of the following curve-hash pairs:
    * P‐256 with SHA-256
    * P‐384 with SHA-384

# UPDATED
Root certificates in our root program, and any certificate which chains up to them, MUST use only algorithms and key sizes from the following set:

* RSA keys whose modulus size in bits is divisible by 8, and is at least 2048.
* Digest algorithms: SHA-1 (see below), SHA-256, SHA-384, or SHA-512.
* ECDSA keys must generate signatures using the hash algorithm specified in the following curve-hash pairs:
    * CA signing key P‐256 MUST sign with SHA-256
    * CA signing key P‐384 MUST sign with SHA-384

**Comment by sleevi** [comment]
@dzacharo Thanks for opening this! It'll be useful to continue to discuss once it gets around to policy updates, but I don't think the updated language is necessarily an improvement - it introduces a new issue in which it can be seen as no restrictions on subscriber keys.

It might be useful if you could document a bit more how you see the current/existing language supporting the ambiguous interpretation. As it stands right now, the current language places restrictions on both the subject keys and the signatures. For example, using SHA-384 with P-256 doesn't seem to have any valid interpretation in the current language to support it, because it's not in the supported list.

Note there's also discussion in #38 and #37 that are highly related. If we treat all three of these issues as one meta-issue, then the suggestion from those other issues seems useful here. Namely, providing an enumerated set of accepted SPKI AlgorithmIdentifier and an enumerated set of accepted Signature AlgorithmIdentifiers, which allows for byte-for-byte comparison without any ambiguity.

**Comment by dzacharo** [comment]
The current language could be interpreted to enforce that regardless of your issuing CA key (say you have a P-384 Issuing CA Key), you can sign a P-256 Subscriber Key with SHA-256. Similarly, if the issuing CA key is P-256, the current language can be interpreted to allow signing a P-384 Subscriber Key with SHA-384.

I do not have a very deep knowledge of all the crypto details but from a policy perspective, a table enumerating all allowed combinations would probably be the best solution. Implementers would be able to take guidance from this table and make sure they get it right with the first try.

I also assume that according to the current policy, it is allowed for an ECDSA Issuing CA to sign an RSA Subscriber Key, as long as the subscriber key meets the RSA requirements set by the policy.

**Comment by sleevi** [comment]
Gotcha! Thanks for explaining.

Yes, the current policy permits mixing and matching algorithms in certificate chains. It would be nice to more narrowly scope that (preferably in the BRs), but there are operational challenges that make that difficult, such as cross-signs and algorithm migration. Within the current set of accepted algorithms (both the BRs and Mozilla Policy), the set of accepted algorithms are considered of comparable cryptoanalytic review and strength, so it's primarily only a concern if introducing support for new algorithms.

The proposal from those other issues was to explicitly enumerate - even with the byte-level encoded representations - the accepted forms for both the SPKI and the Signature AlgorithmIdentifier (and, for some RSA cases, the inner encoding).

**Comment by fotisl** [comment]
I would just like to note that I agree with enumerating the exact accepted AlgorithmIdentifiers with the inner encoding (I guess you are talking about RSA-PSS). Just stating the hashing algorithm will become a real issue, especially if Ed25519ph and Ed448ph gets adopted.

**Comment by dzacharo** [comment]
@sleevi @fotisl, If we all agree we need to explicitly enumerate the allowed combinations, I wouldn't mind proposing or endorsing a ballot for the Baseline Requirements to update section 6.1.5 (with your help of course). However, we would probably need to allow the P-521 curve (as it is currently allowed in the BRs) which is currently not allowed by the Mozilla policy.

If this tasks seems complicated, perhaps we could tweak the updated language I originally proposed in this issue to address the concerns by Ryan and specify the allowed curves for Subscriber Keys in 5.1. 

Does that seem like a workable solution?

**Comment by sleevi** [comment]
Do you believe this is an urgent and pressing issue that needs immediate
resolution?

I ask because changing the BRs will take significantly more effort than
updating the policy. I do not believe the proposed attempt is a positive
step forward, so I do not believe it represents a good starting point. I do
not feel it necessary to tackle this particular issue in a comprehensive
way until the next policy update, which will allow for wider feedback. I do
not believe it appropriate to assume the comments here are sufficient in
themselves.

Given all of the work needed on the BRs, I think it’s perfectly reasonable
to take the following steps:
1) Holisticly review this policy and related issues during the next policy
update, which will include draft language
2) Update this policy with the outcome of this
3) If and as necessary, propose updates to the Baseline Requirements

I do not believe it’s necessary to update the BRs as the way to resolve
this.

**Comment by dzacharo** [comment]
The urgency (or not) could be best determined if someone could scan CCADB/crt.sh to find ECDSA Intermediate CA and end-entity Certificates issued after April 1st 2017 that include an incompatible curve/hash pair according to Mozilla Policy. If the number is high, it is very likely that the policy has been misinterpreted and/or this requirement has not been communicated effectively to the CAs. 

There is an open issue https://github.com/crtsh/certwatch_db/issues/19 but we have no idea if @robstradling has any plans to implement this search filter.

There is always a chance that the CAs interpreted this requirement correctly and ignored it, but I would be surprised if the majority of CAs (that issue ECDSA Certificates) fail to comply with this requirement.

**Comment by sleevi** [comment]
The number, to date, has been very low. It does not seem the CAs who have
read this requirement misinterpreted the requirement - judging by the
incident reports, the majority of CAs seemed to have ignored it.

I’m presently only aware of one CA that misinterpreted the requirement.
It’s a bit surprising, as CAs generally seem to be aware that a signature
algorithm always includes a hash and is produced by a given key (type and
size). With such an understanding, restrictions on signatures are
statements that are content-independent (i.e. it doesn’t matter what you’re
signing), while restrictions on keys are about the content themselves (keys
you are certifying).

In any event, I think the question of policy is best left towards the next
policy update. I do not believe changing the BRs before then will be
productive or helpful - as it either represents significantly more work
either on a technology side, as the BRs are significantly more liberal in
what they allow, or on the policy side to try and restrict the BRs more
than they are today. Rather than doing that, we can simply update the
policy during the next round of policy discussions. This ensures people’s
limited time is best spent on the most critical aspects of policy and
compliance.

**Comment by fotisl** [comment]
As a reminder, previous discussions related to adopting new cryptographic algorithms, such as the discussions at the 40th F2F meeting at Research Triangle Park on adopting post-SHA2 hashing algorithms, had no outcome due to the complexity of the problem. I don't think that the process of adopting specific curve-hash pairs will be easier/faster.

**Comment by xipki** [comment]
Please also consider the SHA3 algorithms.
