### ISSUE TITLE
Require publication of outdated CA policy documents

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#185]
We've found cases where links to a CA's CP and/or CPS in CCADB are broken (i.e. 404). We do not currently archive older versions of policy documents, but there could be a need to refer to them in regard to a specific certificate issued under that version of the policy document.

Consider requiring CAs to maintain links to older versions of all policy documentation.

**Comment by CBonnell** [comment]
To flesh this requirement out a bit, rather than a requirement to host policy documents in perpetuity, can we limit the obligation to those policy documents that are applicable to CA certificate hierarchies that are currently included in the Mozilla root program? Doing so would accomplish the goal of providing completeness in terms of the policy documents for included CA certificates without burdening CA (Organizations) with maintaining policy documents for long-gone roots in their Repository.
