### ISSUE TITLE
Require public discussion when an organization receives a new subCA

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#195]
Policy 2.7 updated section 8.1 to require a public discussion whenever a new organization obtains control of a subCA, but it grandfathers in existing organizations. Consider strengthening this requirement by either:
  1. Require an organization that has not previously undergone a public discussion to go through one upon receiving a new subCA
  2. Require a public discussion any time an organization that does not have roots in the Mozilla program obtains a subCA

**Comment by BenWilson-Mozilla** [comment]
Aren't 1 and 2 above the same?  Is the difference that 1 applies to a newly created/branded CA? (I'm assuming that if security and operations are under an already approved root, that white-labeled CAs wouldn't be covered.)  But I agree, sections 8 and 8.1 could be edited to make them more clear and require public discussion in these circumstances. Maybe an example or two, or explanatory language, could help.

**Comment by sleevi** [comment]
1 and 2 are different. There are CAs in the Mozilla program that have not undergone public discussion - in effect, grandfathered in.

**Comment by BenWilson-Mozilla** [comment]
I am going to flag this as a v.2.8 Mozilla Root Store Policy issue to resolve.  Meanwhile, we could attempt to create an inventory of those who have been grandfathered and are covered by this update.

**Comment by BenWilson-Mozilla** [comment]
What about selecting Option 1 (Require an organization that has not previously undergone a public discussion to go through one upon receiving a new subCA) instead of Option 2 (Require a public discussion any time an organization that does not have roots in the Mozilla program obtains a subCA)? It seems that Option 2 involves more public discussions while Option 1 assumes that once an organization has undergone public discussion for the first subCA, it can receive a second sub CA without public discussion.  Do we need to address situations where a subCA submits a second subCA to a different participant in the Mozilla root program?

**Comment by BenWilson-Mozilla** [comment]
I'm thinking that I might tack on some language in [MRSP section 7.1](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#71-inclusions) after we say, "We will make such decisions through a public process."  It could then say, "This public-review-and-discussion process SHALL also occur for any entity obtaining a CA certificate that has not previously undergone such process."  This could also be worded to trigger public review for any entity that would otherwise be "grandfathered". 

Or is this issue fully encompassed by the work we've done on externally operated third party CAs? 
https://wiki.mozilla.org/CA/External_Sub_CAs_not_Technically_Constrained

@sleevi - off-hand, do you have one or two examples of CA operators that have in effect escaped public review and discussion?
Or might there be a way to determine the entire list of these potentially grandfathered entities?

**Comment by sleevi** [comment]
@BenWilson-Mozilla I believe Visa and Wells Fargo were the examples I was thinking of, although this issue originally started with the DarkMatter approach (which Option 2 tackles) that avoided discussion, and wanting to make sure all loopholes were closed, and any discussions relevant and fresh.

There are still a number of legacy CAs with roots without recent discussions. For example, CyberTrust Japan was last discussed 12 years ago in https://bugzil.la/496863 , FNMT 13 years ago in https://bugzil.la/435736 , Network Solutions 14 years ago in https://bugzil.la/403915 

At least two of these are reportedly transitioning off being independent roots, after repeated compliance issues.

However, to your immediate question of who the policy would impact, it should be a matter of simply examining any independent sub-CAs in the existing program created before this issue was filed, since they will all have been exempted from discussion. You can then further narrow that down by excluding any organizations with roots created in the past 14 years that are in the Mozilla program.

Hopefully that explanation makes sense?

**Comment by BenWilson-Mozilla** [comment]
Public discussion introduced here: https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/r9ZeggoH9KA/m/NZwE3TuYAwAJ
