### ISSUE TITLE
Update minimum audit criteria versions

### ISSUE THREAD

**Issue by wthayer** [mozilla/pkipolicy#197]
I've checked with Jeff Ward on the current minimum versions of WebTrust criteria that we should accept as of 1/1/2020:

WebTrust for CA – instead of 2.0 use 2.2
WebTrust for BL+NSR – instead of 2.2 use 2.4.1
WebTrust for EVSSL – instead of 1.6.0 use 1.6.8

And with Nick Pope for ETSI:

319 411-1 v1.2.2 or higher
319 411-2 v2.2.2 or higher

**Comment by robinalden** [comment]
Those 3 WebTrust criteria documents all share the same effective date 'For audit periods commencing on or after 1 June 2019'.
You plan for these to be the minimum versions you would accept as of 1 January 2020.

For CAs whose audit periods start between 1 January and 31 May I think this means that we MUST do a split audit period in order to comply with your policy, auditing the first part of the 12 month period to an earlier version and the last part of the 12 month period to the versions you state above.

I don't recall us having to do a split period before, although perhaps that is because dates had fallen favourably for us previously, or because my recollection is faulty.

Split audit periods are achievable, of course, but I wanted to check that the insistence on split audit periods was an intended consequence of your choice of minimum required versions of WebTrust criteria.

**Comment by wthayer** [comment]
@robinalden requiring split audit periods is not the intent. I'll ask the WebTrust folks about this and get back to you.

**Comment by wthayer** [comment]
Thanks @robinalden Based on your comments and discussion with the WebTrust folks, I've moved the minimum versions back one so that they reflect the requirements for audit periods beginning on Oct 1, 2018 (annual + 3 months to submit the report)
