### ISSUE TITLE
Updated ETSI section of Mozilla Root Store Policy

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#202]
Proposal: Change https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy#3122-etsi 
from
~~ Current ~~
For the SSL trust bit, a CA and all subordinate CAs technically capable of issuing server certificates must have one of the following audits, with at least one of the noted policies or sets of policies:
- ETSI EN 319 411-1 (LCP and (DVCP or OVCP)) and/or (NCP and EVCP)
- ETSI EN 319 411-2 (QCP-w)
An audit showing conformance with the EVCP policy is required if issuing EV certificates.
~~~~
to
~~ PROPOSED ~~
For the SSL trust bit to be set a CA needs to claim
ETSI EN 319 411-2 QCP-w or
ETSI EN 319 411-1 EVCP or
ETSI EN 319 411-1 DVCP or
 ETSI EN 319 411-1 OVCP.
~~~~~~~

Explanation:
The audit for a CA claiming conformance to
ETSI EN 319 411-2 QCP-w incorporates all policy requirements of EVCP.
ETSI EN 319 411-1 EVCP requires the auditor to consider the relevant aspects of the policy NCP as referred to in EN 319 411-1.
ETSI EN 319 411-1 DVCP requires the auditor to consider the relevant aspects of the policy LCP as referred to in EN 319 411-1.
ETSI EN 319 411-1 OVCP requires the auditor to consider the relevant aspects of the policy LCP as referred to in EN 319 411-1.

**Comment by WilsonKathleen** [comment]
Argument against making this proposed change:

There are different opinions on this matter, such as:
Group A: "QCP-w includes all of the normative requirements of EVCP, plus those additional for Qualified Certificates"
Group B: "QCP-w is not the same, because it allows for the issuance of QWACs to LCPs, which EVCP does not allow" (Specifically, see REG-6.2.2-04, which acknowledges QCP-w can be used with LCP, as well as the referenced OVR-5.1-03)
Group C: "QCP-w is not the same, because it doesn't necessarily mean all of the EVCP requirements have been incorporated when they're superceded by a QCP-w requirement" (e.g. the PSD2 overriding)

The current Mozilla policy language requires an explicit statement of conformity against EVCP, rather than to accept implicitly QCP-w as including EVCP, since they're not a direct 1:1 mapping.

**Comment by WilsonKathleen** [comment]
Additional discussion about QCP-w and EVCP is in Bugzilla bug #1585951 beginning with Comment 23.
https://bugzilla.mozilla.org/show_bug.cgi?id=1585951#c23
In particular, note comment 25: 
"QCP-w allows the issuance of certificates to individuals under the QCP-w profile, while the EV guidelines do not permit such issuance."
"things forbidden by the EV Guidelines are indirectly permitted by QCP-w."
"QCP-w is more broad than EVCP, it's not sufficient or equivalent to simply accept QCP-w."

**Comment by dzacharo** [comment]
The fact that QCP-w describes a case where a Natural Person may own a Trust Service Provider and may issue a QCP-w QWAC (which is not an EV TLS Certificate), doesn't mean that Mozilla doesn't have enough evidence or assurances regarding the TSP's competence and compliance for EVCP practices/procedures related to the issuance of EV TLS Certificates. One does not exclude the other.

Put differently, a QTSP that has been certified for QCP-w, meets all the expectations for EVCP which includes the practices/policies for the issuance and management of EV TLS Certificates, which is what Mozilla and other Root Programs are looking for. IMHO the fact that the QTSP (under the QCP-w policy) may also issue a QWAC for a natural entity under a hierarchy which is not publicly trusted, should not be a concern for Mozilla.

**Comment by sleevi** [comment]
> IMHO the fact that the QTSP (under the QCP-w policy) may also issue a QWAC for a natural entity under a hierarchy which is not publicly trusted, should not be a concern for Mozilla.

I can appreciate that, as a CA, that is a natural perspective, as CAs often begin from a position where they trust themselves. An audit exists precisely because browsers do not trust CA’s word, and need independent, third-party assurance that meets the browser’s needs, not the CA’s needs.

In a situation like this, the existence of solely QCP-w does not provide assurance, for example, that a given policy associated with QCP-w is only used for Legal persons in conjunction with EVCP. It also allows for situations in which QCP-w directly or indirectly overrides a requirement of EVCP, as we have seen in the case of PSD2.

Much like some CAs have not seen the need for the inclusion of SHA-1/SHA-256 thumbprints of i -scope CAs in their audits, and much like some auditors have not seen the necessity for including all in-scope CAs, at the end of the day, the audit report used by Mozilla and other browsers needs to satisfy those browser’s needs. A report only stating QCP-w has enough ambiguity, and enough potential loopholes, to represent real and concrete risk.

CAs that comply with all the provisions of EVCP should be able to easily report this, in addition to their QCP-w, and should be able to easily identify the policy/policies used exclusively for EVCP, preferably the CABF OID.

**Comment by dzacharo** [comment]
I'm not sure I follow. The QCP-w scope (of ETSI EN 319 411-2) includes the EVCP scope of ETSI EN 319 411-1. The CA is audited against that criteria and is deemed competent and is certified if everything is good. Isn't this what a Browser would need to rely on in order to justify their belief that the CA is competent of issuing EV TLS Certificates according to the EV Guidelines?

Have you seen a case where a CA is certified for QCP-w which is not in scope of EVCP (e.g. has only been certified to issue QCP-w Certificates for "Natural Entities")? It would be a very extreme case and I haven't had a chance to see such a case.

BTW, I don't have any strong feelings about this but I think the argument that QCP-w certification scope might not include the EVCP scope, is quite confusing (at least to me).

**Comment by sleevi** [comment]
> The QCP-w scope (of ETSI EN 319 411-2) includes the EVCP scope of ETSI EN 319 411-1.

With exceptions and modifications not permitted by EVCP. QCP-w explicitly allows things that are forbidden by EVCP. Just because it requires EVCP in some places does not mean it is compatible.

**Comment by sleevi** [comment]
> Have you seen a case where a CA is certified for QCP-w which is not in scope of EVCP (e.g. has only been certified to issue QCP-w Certificates for "Natural Entities")?

It does not matter. The ability to issue QCP-w for such entities - forbidden by EVCP - is enough of a problem. Just because they also issue to legal entities under EVCP, the ability to issue to natural entities means that QCP-w allows things EVCP forbids. EVCP is more restrictive in that regard, even though QCP-w is more restrictive in other areas.

**Comment by dzacharo** [comment]
> It does not matter. The ability to issue QCP-w for such entities - forbidden by EVCP - is enough of a problem.
I think this is the core of our disagreement and I'm trying to be careful not to make things more confusing. 

You say that CAs that are certified for QCP-w **AND** EVCP are problematic because one "contradicts" the other, and I say that CAs that are certified for both, have procedures and processes in place for the different cases (issue to natural persons which is not following all the EV Guidelines or issue to legal entities which is following all of the EV Guidelines). The former is incompatible with the EV Guidelines and would be considered a mis-issuance in the Mozilla Root store Policy. But if the CA is chaining these Certificates to a non-publicly-trusted Root, I don't think that would be a problem.

Of course the CA must be careful what to issue in each case but the Audit Attestation should be proof that the CA is competent to do both.

**Comment by sleevi** [comment]
> But if the CA is chaining these Certificates to a non-publicly-trusted Root, I don't think that would be a problem.

Nothing about the audit says that condition is being met... unless we require the audit letter clearly specify EVCP, as done currently.

> Of course the CA must be careful what to issue in each case but the Audit Attestation should be proof that the CA is competent to do both.

It isn’t, because it does not provide assurance that the CA was careful in what they issued.

That’s the reality of it. QCP-w serves a different purpose. If EVCP is meant, then a letter clearly stating so follows. There is zero benefit, to a browser root store operator, from accepting something only indicating the QCP-w criteria.

**Comment by ArnoFie** [comment]
> 
> 
> Argument against making this proposed change:
> 
> There are different opinions on this matter, such as:
> Group A: "QCP-w includes all of the normative requirements of EVCP, plus those additional for Qualified Certificates"
> Group B: "QCP-w is not the same, because it allows for the issuance of QWACs to LCPs, which EVCP does not allow" (Specifically, see REG-6.2.2-04, which acknowledges QCP-w can be used with LCP, as well as the referenced OVR-5.1-03)
> Group C: "QCP-w is not the same, because it doesn't necessarily mean all of the EVCP requirements have been incorporated when they're superceded by a QCP-w requirement" (e.g. the PSD2 overriding)
> 
> The current Mozilla policy language requires an explicit statement of conformity against EVCP, rather than to accept implicitly QCP-w as including EVCP, since they're not a direct 1:1 mapping.
-------------
Feedback from Nick and Arno:
Statement A is correct with minor clarification: QCP-w WHEN ISSUED TO LEGAL PERSONS includes all the requirements of EVCP, plus additional requirements.  When issued to a natural person it is considered to be outside the scope of CAB Forum and is based on the NCP.

Statement B: is incorrect as QCP-w conformant cannot apply LCP.

Statement C: is partially true.  EVCP does not apply to certificates issued to natural persons.   PSD2 certificates can currently conform to EVCP as there is currently no conflict between the PSD2 requirements and EVCP but if there is a divergence PSD2 requirements take precedence. 

It is recommended that TSPs wishing to issue qualified certificates and conform to CAB Forum EV include both  QCP-w and EVCP in the scope of the audit.  Thus, your current policy is correct.

**Comment by WilsonKathleen** [comment]
I'm closing this issue as won't fix, based on Arno's input:
> It is recommended that TSPs wishing to issue qualified certificates and conform to CAB Forum EV include both QCP-w and EVCP in the scope of the audit. Thus, your current policy is correct.
