### ISSUE TITLE
Require audit statements to provide information about which CA Locations were audited

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#207]
Audit statements should provide information about which CA Locations were and were not audited, and the extent to which they were (or were not) audited.

This is being discussed here:
https://groups.google.com/d/msg/mozilla.dev.security.policy/4Q6WAgLAvDo/MJsbc73TAgAJ

And added to this wiki page:
https://wiki.mozilla.org/CA/Audit_Statements#Audit_Delay

This should also end up in the BRs at some point, in addition to being in Mozilla's policy (some CAs in Mozilla's program do not issue TLS certs).

**Comment by sleevi** [comment]
Depending on the timing, this could either
1. Be folded into the [Browser alignment ballot](https://github.com/cabforum/documents/compare/master...sleevi:2019-10-Browser_Alignment) for the BRs
2. Slot nicely into that Section 8.6 if the ballot is adopted

**Comment by BenWilson-Mozilla** [comment]
We should add this requirement to [section 3.1.4 of the Mozilla Root Store Policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#314-public-audit-information) maybe with some cross references to things such as the Audit Delay guidance ([Minimum Expectations](https://wiki.mozilla.org/CA/Audit_Statements#Minimum_Expectations)) mentioned above.

**Comment by JeffWardPKI** [comment]
The underlying obstacle for this disclosure is the fact that there is no clear definition of “CA Location” in the BRs. There are numerous locations considered during an audit, such as locations that store CA private keys, locations where vetting is performed, locations hosting RA and other services, and OCSP responder locations, to name a few. Since it is unclear how “location” is defined, it is difficult for audit firms to apply this concept in a consistent manner.  For instance, would auditing a location include more than physical security controls? Are there additional considerations? If only physical security controls are considered, there are no physical security requirements in the BRs, Section 5.1. 

Thanks, 

Jeff Ward

**Comment by BenWilson-Mozilla** [comment]
@JeffWardPKI  Just thinking out loud here - we would want the locations at which the CA is normally audited for its controls protecting the physical security of its operations facilities and data centers--meaning the general geographic area or region at the sub-national administrative division or subdivision level, such as a village, town, borough, city, state, province, canton, county, governorate, or oblast (or alternatively it could be said that a facility is "near" one of the foregoing if it is not precisely within such jurisdictional boundaries).  We're certainly not looking for street addresses. If multiple facilities are located in the same general area or region, then further description of the facility should be provided. In the WebTrust audit letter templates, there is a spot for the CA's location, so this should not be anything new. We should, however, see what we can do to address audit delays due to pandemics and other similar occurrences.  And for anyone following this thread here in Github, I intend to improve the current language and send this issue to the m.d.s.p. list for discussion sometime later this week.
