### ISSUE TITLE
Require CRLReason for all revocations

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/pkipolicy#208]
Require CAs to provide a CRLReason for all revocations -- end-entity certs and intermediate certs.

[Discussion in m.d.s.p](https://groups.google.com/d/msg/mozilla.dev.security.policy/nU1bIZ9LgjU/8RxqN_zsAgAJ) indicates that some CAs have Terms and Conditions which say that if the customer moves to (or even tries to use) another CA, all of their certificates will be revoked. Enforcing all revocations (independent of reason) supports this bad behavior by CAs, helping them to hold their customers hostage. But if CAs always add the CRLReason for revocations, we can selectively enforce revocation for certain reasons, and have varying levels of enforcement (e.g.  overridable versus not-overridable)

**Comment by WilsonKathleen** [comment]
https://tools.ietf.org/html/rfc5280#section-5.3.1 
"the reason code CRL entry extension SHOULD be absent instead
   of using the unspecified (0) reasonCode value."

**Comment by wthayer** [comment]
What prevents a CA [that is already behaving poorly] from simply choosing a revocation reason that Firefox enforces?

Also, I am not aware of and agreed-upon definitions for the reasons listed in 5280. For example, what does "privilegeWithdrawn" mean and do you think everyone interprets it the same way. I'd suggest that a prerequisite for Mozilla beginning to rely on revocation reasons is to define the meaning and acceptable usage for whatever subset of reasons Mozilla chooses to support.

**Comment by sleevi** [comment]
I agree with Wayne: the most useful prerequisite is assigning the meaning
and valid uses (which is expanded upon in ITU-T X.509 but omitted from
PKIX), and then requiring that (if?) a reason is included, it aligns with
those definitions / uses.

**Comment by robinalden** [comment]
Selective implementation of revocation based on the concept of there being 'good' and 'bad' revocation reasons has an implicit challenge.  It changes the certificate life-cycle. 

Simplistically, the life of a certificate today is either: 
Issue - use - expire; or 
Issue - use - revoke, 
and in each case no further management of the certificate's state is possible by either the CA or the subscriber after the terminal event.  However, if there are 'bad' revocations that will be ignored the life-cycle gets another step under certain circumstances: 
Issue - use - 'bad' revocation (ignored) - use - 'good' revocation.
This requires both that the user is able to request a second revocation for a different reason after an earlier revocation, and also that the CA has further obligations to take actions concerning this certificate after it had been initially revoked, e.g. re-revoking if misissuance or subscriber key compromise were detected.

**Comment by RufusJWB** [comment]
I think a CRL-filtering mechanism as proposed is 'overengineering', especially since it would need to be implemented by a substantial amount of certificate consumers to be really useful. Instead of such a mechanism, I would simply add a requirement to the Root Store Policy like the following:

> Any participating CA acknowledges that issued certificates are in the ownership of the subscriber and SHALL only be revoked according to the reasons described in CA/B BRGs chapter 4.9.1.1. 

Of course there is still reason 10 in that list and a clever CA could put a sentence "we revoke all your certificates if you leave us" into the CP/CPS, but I think 99% of the cases would be covered.

**Comment by sleevi** [comment]
Rufus, Robin: Would it make sense to chime in on the m.d.s.p. thread, to
continue discussion with all participants?

**Comment by RufusJWB** [comment]
I would love to, but as you know, I'm not allowed to post on mdsp :-( But please go ahead, I'm optimistic I'll find a way to forward my opinion to the mailing list.

**Comment by robinalden** [comment]
Sure, happy to.



Regards
Robin Alden

Sectigo Limited

**Comment by BenWilson-Mozilla** [comment]
See discussion here https://groups.google.com/forum/#!topic/mozilla.dev.security.policy/nU1bIZ9LgjU

**Comment by BenWilson-Mozilla** [comment]
I recommend we close this issue because section 7.2.2 of the Baseline Requirements (v.1.7.1) now specifies, 

1. reasonCode (OID 2.5.29.21)
Effective 2020-09-30, all of the following requirements MUST be met:
If present, this extension MUST NOT be marked critical.
If a CRL entry is for a Root CA or Subordinate CA Certificate, including Cross Certificates, this CRL entry extension MUST be present. If a CRL entry is for a Certificate not technically capable of causing issuance, this CRL entry extension SHOULD be present, but MAY be omitted, subject to the following requirements.
The CRLReason indicated MUST NOT be unspecified (0). If the reason for revocation is unspecified, CAs MUST omit reasonCode entry extension, if allowed by the previous requirements. If a CRL entry is for a Certificate not subject to these Requirements and was either issued on-or-after 2020-09-30 or has a notBefore on-or-after 2020-09-30, the CRLReason MUST NOT be certificateHold (6). If a CRL entry is for a Certificate subject to these Requirements, the CRLReason MUST NOT be certificateHold (6).
If a reasonCode CRL entry extension is present, the CRLReason MUST indicate the most appropriate reason for revocation of the certificate, as defined by the CA within its CP/CPS.
