### ISSUE TITLE
CABF EV OID must appear 1st in End Entity Certificates

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [mozilla/pkipolicy#248]
The MRSP should be amended to specify that the CABF EV OID must be the first OID in end entity certificates, as per https://wiki.mozilla.org/CA/EV_Processing_for_CAs#First_OID

**Comment by sleevi** [comment]
@BenWilson-Mozilla Thanks for filing this! I wasn’t aware that Mozilla had documented their behavior for this.

This is currently part of the mandatory part of the cert profiles work, and there had been pushback about removing that requirement, rather than deferring it (until October).

Would Mozilla be supportive of introducing it to the BRs, with an effective date of October (with the other profiles changes)? That doesn’t preclude you from adding it to MRSP, but since it’s already part of the draft profiles work, we could just keep it there with an effective date, rather than remove it.

**Comment by BenWilson-Mozilla** [comment]
> 
Yes - we can do that.

**Comment by WilsonKathleen** [comment]
Note that this will not be needed if Bugzilla [Bug #1769150](https://bugzilla.mozilla.org/show_bug.cgi?id=1769150) is implemented.

**Comment by sleevi** [comment]
In the linked discussion, the “first policy should be a CABF policy” was removed from the initial version. Although Firefox is not the only implementation to use the “first matching policy” logic (both Apple and Chrome had or still have similar logic, so it is widespread), for CAs that haven’t been granted the CABF EV policy OID in addition to their per-CA policy OID (e.g. for legacy roots), it’s necessary to use the per-CA OID first.

Thus, there’s no “great” answer, as either ordering means EV treatment in some browsers, but not others, until all CA Certificates operated by a CA have the CABF OID.

**Comment by BenWilson-Mozilla** [comment]
I think this can be closed because all OIDs are now checked per Bugzilla [Bug #1769150](https://bugzilla.mozilla.org/show_bug.cgi?id=1769150).
