### ISSUE TITLE
Require that audit reports disclose all root and intermediate certificates in scope

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#28]
We should require that some public part of the audit report (management assertions or auditor's letter) list all the root and intermediate certificates which were in scope for the audit.

**Comment by sleevi** [comment]
@gerv From discussing with auditors, they had a number of reasonable concerns, similar to the concerns they've expressed with respect to RAs.

For example, some auditors expressed concern that they do not believe they can opine on others' attestation letters, which is effectively what would be stated by incorporating into the auditors' assertion.

Other auditors raised concerns that because it's a period of time, there will always be a period of time in which the subordinate CAs are not audited - unless you synchronize all audits precisely, which becomes messy with cross-signs (where you have two issuing CA's under audit that have to be synchronized). That is, consider CA A who is audited 2015-1-1 to 2015-12-31, but who has a sub-CA, CA B, that is audited 2015-6-1 to 2016-5-31. Then the auditor for CA A prepares their report, they cannot make statements about CA B for the period of 2015-6-1 to 2015-12-31 until the report is prepared, sometime after 2016-5-31.

Finally, some auditors expressed concern about their ability to report on the facts. For example, if managements assertions disclosed CAs A, B, and C, but the auditor knew of CA D through their engagement, they would not be able to materially disclose the existence of that CA D, because it was covered under the confidentiality of their engagement, and management could carefully and creatively word such a management report to avoid the disclosure of D.

This is why, during the CA/Browser Forum F2F, I suggested incorporation into CP/CPS as a different approach, which places all of the burdens of that on the issuing CA. But I don't feel like we've got a workable solution yet to make me comfortable declaring by fiat, so much as wanting to still work with auditors and CAs to best understand how to materially, and auditably, get to this point.

**Comment by gerv** [comment]
OK. I'll take this out of scope for 2.4, and let you continue to work on the best solution :-)

**Comment by gerv** [comment]
Hmm. Looks like I can't assign things to you. Perhaps you need to be a member of the mozilla organization and/or a member of the pkipolicy team :-|

**Comment by gerv** [comment]
@sleevi: any update here?

**Comment by WilsonKathleen** [comment]
To clarify... We want to know which certificates were in scope of the audit. 

Example: When a subCA is not in scope of an audit, then there should be a separate audit statement for that subCA, and the CA should *not* check the "Audits Same as Parent" box in the CCADB for that subCA, but rather provide the separate audit info for it.

**Comment by sleevi** [comment]
Yeah, that was a misunderstanding on my part, thinking it was about disclosure of what's _not_ in scope or that the full hierarchy is disclosed.

**Comment by sleevi** [comment]
Note that the above remarks re: RAs imply that a given audit statement _only_ includes the CA's operations, and makes no opinions about the sub-CAs operated or about the RAs operated, nor do they opine that the sub-CA has 'current' audits.

**Comment by gerv** [comment]
OK. This will be fixed when we fix #58.
