### ISSUE TITLE
Consider sunsetting domain name ownership validations not done by 10-Blessed-Method-compatible means

### ISSUE THREAD

**Issue by gerv** [mozilla/pkipolicy#92]
Many domain name ownership validations from the past were not done by 10-Blessed-Method-compatible means. We should consider telling CAs that such validations have a shorter lifetime than the standard age-out lifetime, so we can get the suspect stuff out of the system sooner.

**Comment by sleevi** [comment]
I'm guessing this public bug is your implicit confirmation of what was shared on the CA/Browser Forum call on 2017-07-06

Which is that, despite the provisions in https://github.com/mozilla/pkipolicy/blob/master/rootstore/policy.md#22-validation-practices , CAs are permitted to use any method they desire to validate domains, and may continue issuing certificates for those domains (and their subdomains) up to the maximum time permitted by the Baseline Requirements, provided they do so prior to 21 July 2017.

This is despite having multiple CAs, such as WoSign, have notable security issues with file-based demonstration of control - and no appropriate guidance until the adoption on 169 as to what was acceptable.

**Comment by gerv** [comment]
Yes. As noted on the call, I don't see how we can distinguish between secure and insecure pre-169 implementations of file-based demonstrations of control, and I doubt the ballot will pass if we just tell CAs to junk all their pre-existing validations. Suggestions for how to cut this Gordian knot are welcome; this bug represents one suggestion.

**Comment by gerv** [comment]
And yes, I guess I know I can just tell them to junk them all by fiat, as it's our policy. I'm currently not prepared to do that. I think the risk (based on the validation _method_) of a 2-year-old domain validation is very low. If someone was going to do something nefarious with it, it would have already happened.

**Comment by sleevi** [comment]
I suppose I had believed, based on the present wording of 2.5, that Mozilla had cut that Gordian Knot by setting the deadline as 21 July 2017 for when, in the process of issuing new certificates, they use the appropriate methods. This aligned with past discussion in Seattle and Raleigh, but it appears I misunderstood.

**Comment by gerv** [comment]
Yes, they are no longer allowed to use the old methods to do validations, as of that date. That is not the same thing as reusing a validation done using an old method. If we were setting a deadline for that, it would not have been 3 months after we set it.

**Comment by sleevi** [comment]
Historically, Mozilla policy has not made any distinction between
"validation", "revalidation", or "reused validation", much like it did not
recognize "rekey" as a distinct action from "issuance". Hence the
confusion, as this is a notable divergence from one might expect.

Still, at least it's clarified.

**Comment by floatingatoll** [comment]
Is the key distinction here that a "validation method" is being retired,
such that the distinction issues with "validation" simply don't apply, as
no effect occurs to any interpretation of it?

**Comment by sleevi** [comment]
I'm not sure I fully parse that, but an attempt to state it differently:

In the past, some CAs took the view that the issuance of a certificate with a distinct key is a "rekey", and thus does not constitute a certificate being issued (or, more aptly, that it's distinct from the issuance of a certificate), and thus policies related to the issuance of a certificate don't apply. This was most notable with respect to various 'sunsets' - and the view that it was acceptable to issue a certificate 'the same' (or "mostly" the same) as a previous certificate, with a new key, and not be subject to any new policies. Mozilla rejected this interpretation, as the issuance of a certificate is, well, the issuance of a certificate.

Related to this discussion, it's a question about whether 'validation' is expected to occur every time a certificate is issued, or whether it is a distinct and independent step. CAs have, apparently, viewed validation as a distinct and different step than issuance. Put differently, there's no obligation to validate the domain on the issuance of a certificate, just that, 'at some point', the domain was validated. Further, even if this validation was not permissible by the current BRs, it was OK to issue the certificate, because the validation was presumably permissible at the time it was performed.

The alternative view is that 'validation' of the included domains happens every time a certificate is issued, and all domains must be validated in a manner conforming to the BRs at the time the certificate issues. The reuse permits reusing data and documents used for that validation, or the validation itself (provided it's still allowed), but not the use of retired methods.

To support Gerv's view of the policy (which, to be clear, is authoritative), one has to view validation as something not done on every issuance. I was simply highlighting that it seems of the same logical vein as the CAs that argued 'rekey' was not 'new' issuance, and hence a surprising conclusion - but it is the conclusion.

**Comment by floatingatoll** [comment]
There's a wording conflict above between "validation" (the process) and "validation" (a single instance thereof, executed at a single point in time). So, using clumsy wording, I would restate this as:

A single "validation method" was deprecated for use going forward from 21 Jul. Should any "validation instances" that used that method be invalidated prior to their normal expiration? Should "validation instances" be reusable in this way at all?

**Comment by floatingatoll** [comment]
I think in my words 'validation instances' are simply called 'validations' above, but I don't know what 'validation methods' translate to in the wording above. Maybe 'validation'? That confusion is what I was trying to convey and somehow untangle.

**Comment by BenWilson-Mozilla** [comment]
I believe that this issue can be closed because several sunset periods have since passed in section 3.2.2.4 of the CABF's Baseline Requirements.
